load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "hello-time",
    srcs = ["hello-time.cpp"],
    hdrs = ["hello-time.hpp"],
)

cc_library(
    name = "database_client",
    srcs = ["database_client.cpp"],
    hdrs = ["database_client.hpp"]
)