repos:
  - repo: https://github.com/pennlabs/pre-commit-hooks
    rev: v1.0-mobile-backend
    hooks:
      - id: black
        args: []
      - id: isort
        args: []
      - id: flake8
        args: [--config, setup.cfg]
      - id: detect-private-key