#!/bin/sh
set -e

echo "********************* Running isort *********************"
isort ./src 
echo "********************* Running black *********************"
black -l100 ./src
echo "********************* Running flake8 ********************"
flake8 ./src
